# Netlify Build Configuration
[build]
  # No build command needed - static files only
  command = ""
  publish = "."
  
  # Environment variables (if needed)
  # [build.environment]
  #   NODE_ENV = "production"

# Redirect rules for SPA behavior (if needed in future)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://www.google-analytics.com;"

# Cache control for static assets
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Force HTTPS
[[redirects]]
  from = "http://ifuckinghaterscrum.netlify.app/*"
  to = "https://ifuckinghaterscrum.netlify.app/:splat"
  status = 301
  force = true

# Custom domain redirects (when you set up custom domain)
# [[redirects]]
#   from = "https://ifuckinghaterscrum.com/*"
#   to = "https://www.ifuckinghaterscrum.com/:splat"
#   status = 301
#   force = true
